name: Docker Image CI for GHCR

on:
  push

jobs: 
  build_and_publish:
  runs-on: ubuntu-latest
  steps:
    - uses: action/checkout@v3
    - name: Build and pudh the Image
      run:
        docker login --username darioDTU --password ${{secrets.GH_PAT}} ghcr.io
        docker build . --tag ghcr.io/dariodtu/anomalies_detection:latest
        docker push --tag ghcr.io/dariodtu/anomalies_detection:latest
