name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push backend image
        run: |
          docker login --username patrizioDK --password ${{secrets.AD_GIT}} ghcr.io
          docker build -f backend/Dockerfile backend -t ghcr.io/patriziodk/anomalies_detection_backend:1.0.0
          docker push ghcr.io/patriziodk/anomalies_detection_backend:1.0.0

      - name: Build and push frontend image
        run: |
          docker build -f frontend/Dockerfile frontend -t ghcr.io/patriziodk/anomalies_detection_frontend:1.0.0
          docker push ghcr.io/patriziodk/anomalies_detection_frontend:1.0.0
