name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs: 
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the Image
        run: |
          docker login --username darioDTU --password ${{secrets.GH_PAT}} ghcr.io
          docker build . --tag ghcr.io/dariodtu/anomalies_detection:latest
          docker push ghcr.io/dariodtu/anomalies_detection:latest
