name: Docker Image CI for GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push frontend image
        run: |
          docker build -f frontend/Dockerfile frontend -t ghcr.io/dariodtu/anomalies_detection_frontend:1.0.0
          docker push ghcr.io/dariodtu/anomalies_detection_frontend:1.0.0
